version: "3.3"
services:
          
  eureka:
    image: eureka-local:latest
    build: 
      context: ../../eureka
      dockerfile: Dockerfile
    networks:
      - colmena-net
    ports:
      - "7000:7000"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: always
        
  config-server:
    image: config-server-local:latest
    build: 
      context: ../../config-server
      dockerfile: Dockerfile
    networks:
      - colmena-net
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - eureka
    restart: always

  proxy:
    image: zuul-proxy-local:latest
    build: 
      context: ../../zuul
      dockerfile: Dockerfile
    networks:
      - colmena-net
    ports:
      - "7001:7001"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - eureka
      - config-server
    restart: always

  colmena-audit:
    image: colmena-audit-local:latest
    build: 
      context: ../../colmena-audit
      dockerfile: Dockerfile
    networks:
      - colmena-net
    ports:
      - "8001:8001"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - eureka
      - config-server
    restart: always

  colmena-github-webhook:
    image: github-webhook-local:latest
    build: 
      context: ../../colmena-github-webhook
      dockerfile: Dockerfile
    networks:
      - colmena-net
    ports:
      - "7100:7100"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - git-user=mdd-utn
      - token-access=fc71faf6b51951bc1142932f5850c8974370998a
      - token=11
    depends_on:
      - eureka
      - config-server
    restart: always
  
  
  colmena-reverse:
    image: colmena-reverse-local:latest
    build: 
      context: ../../colmena-reverse
      dockerfile: Dockerfile
    networks:
      - colmena-net
    ports:
      - "7900:7900"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - eureka
      - config-server
    restart: always
    
  static:
    image: colmena-resource-server
    build: 
      context: ../../colmena-resources-server
      dockerfile: Dockerfile
      args:
       buildno: 1
    volumes:
    - ../../colmena-audit/src/main/resources/static:/usr/share/nginx/static/colmena-audit/static
    ports:
    - "80:80"
    environment:
    - NGINX_HOST=static
    - NGINX_PORT=80
    restart: always
    networks:
      - colmena-net
        
networks:
  colmena-net: